"use strict";
var canvas_1 = require('./canvas');
exports.Canvas = canvas_1.default;
var animated_canvas_1 = require('./animated_canvas');
exports.AnimatedCanvas = animated_canvas_1.default;
var scales = require('./scales');
exports.scales = scales;
var react_1 = require('./react');
exports.CanvasComponent = react_1.CanvasComponent;
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = animated_canvas_1.default;
